
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: deploy/Dockerfile.streamlit
    ports:
      - "8000:8000"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: deploy/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend